config/routes.rb
Rails.application.routes.draw do
  resources :organization_contracts

  resources :organizations

  resources :user_events

  resources :users

  resources :event_facebook_pages

  resources :events

  resources :facebook_pages

end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base
  self.table_name = 'UserEvents'

  belongs_to :user
  belongs_to :event
end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController
  before_action :set_user_event, only: [:show, :edit, :update, :destroy]

  # GET /user_events
  # GET /user_events.json
  def index
    @user_events = UserEvent.all
  end

  # GET /user_events/1
  # GET /user_events/1.json
  def show
  end

  # GET /user_events/new
  def new
    @user_event = UserEvent.new
  end

  # GET /user_events/1/edit
  def edit
  end

  # POST /user_events
  # POST /user_events.json
  def create
    @user_event = UserEvent.new(user_event_params)

    respond_to do |format|
      if @user_event.save
        format.html { redirect_to @user_event, notice: 'User event was successfully created.' }
        format.json { render :show, status: :created, location: @user_event }
      else
        format.html { render :new }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_events/1
  # PATCH/PUT /user_events/1.json
  def update
    respond_to do |format|
      if @user_event.update(user_event_params)
        format.html { redirect_to @user_event, notice: 'User event was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_event }
      else
        format.html { render :edit }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_events/1
  # DELETE /user_events/1.json
  def destroy
    @user_event.destroy
    respond_to do |format|
      format.html { redirect_to user_events_url, notice: 'User event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_event
      @user_event = UserEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_event_params
      params.require(:user_event).permit(:user_id, :event_id, :created_dt)
    end
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/views/user_events/_form.html.erb
<%= form_for(@user_event) do |f| %>
  <% if @user_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_event.errors.count, "error") %> prohibited this user_event from being saved:</h2>

      <ul>
      <% @user_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :created_dt %><br>
    <%= f.datetime_select :created_dt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_events/edit.html.erb
<h1>Editing User Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_event %> |
<%= link_to 'Back', user_events_path %>

app/views/user_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Events</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event</th>
      <th>Created dt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_events.each do |user_event| %>
      <tr>
        <td><%= user_event.user_id %></td>
        <td><%= user_event.event_id %></td>
        <td><%= user_event.created_dt %></td>
        <td><%= link_to 'Show', user_event %></td>
        <td><%= link_to 'Edit', edit_user_event_path(user_event) %></td>
        <td><%= link_to 'Destroy', user_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User event', new_user_event_path %>

app/views/user_events/new.html.erb
<h1>New User Event</h1>

<%= render 'form' %>

<%= link_to 'Back', user_events_path %>

app/views/user_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_event.user_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @user_event.event_id %>
</p>

<p>
  <strong>Created dt:</strong>
  <%= @user_event.created_dt %>
</p>

<%= link_to 'Edit', edit_user_event_path(@user_event) %> |
<%= link_to 'Back', user_events_path %>