config/routes.rb
Rails.application.routes.draw do
  resources :organization_contracts

  resources :organizations

  resources :user_events

  resources :users

  resources :event_facebook_pages

  resources :events

  resources :facebook_pages

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :events, foreign_key: :org_id
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:org_src_id, :org_id, :account_type_id, :created_dt, :modified_dt, :created_by_user_id, :modified_by_user_id, :target_marketer_bit, :target_marketer_subscription_pricing_id, :target_marketer_billing_user_id)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :org_src_id %><br>
    <%= f.number_field :org_src_id %>
  </div>
  <div class="field">
    <%= f.label :org_id %><br>
    <%= f.number_field :org_id %>
  </div>
  <div class="field">
    <%= f.label :account_type_id %><br>
    <%= f.number_field :account_type_id %>
  </div>
  <div class="field">
    <%= f.label :created_dt %><br>
    <%= f.datetime_select :created_dt %>
  </div>
  <div class="field">
    <%= f.label :modified_dt %><br>
    <%= f.datetime_select :modified_dt %>
  </div>
  <div class="field">
    <%= f.label :created_by_user_id %><br>
    <%= f.number_field :created_by_user_id %>
  </div>
  <div class="field">
    <%= f.label :modified_by_user_id %><br>
    <%= f.number_field :modified_by_user_id %>
  </div>
  <div class="field">
    <%= f.label :target_marketer_bit %><br>
    <%= f.check_box :target_marketer_bit %>
  </div>
  <div class="field">
    <%= f.label :target_marketer_subscription_pricing_id %><br>
    <%= f.number_field :target_marketer_subscription_pricing_id %>
  </div>
  <div class="field">
    <%= f.label :target_marketer_billing_user_id %><br>
    <%= f.number_field :target_marketer_billing_user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Org src</th>
      <th>Org</th>
      <th>Account type</th>
      <th>Created dt</th>
      <th>Modified dt</th>
      <th>Created by user</th>
      <th>Modified by user</th>
      <th>Target marketer bit</th>
      <th>Target marketer subscription pricing</th>
      <th>Target marketer billing user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.org_src_id %></td>
        <td><%= organization.org_id %></td>
        <td><%= organization.account_type_id %></td>
        <td><%= organization.created_dt %></td>
        <td><%= organization.modified_dt %></td>
        <td><%= organization.created_by_user_id %></td>
        <td><%= organization.modified_by_user_id %></td>
        <td><%= organization.target_marketer_bit %></td>
        <td><%= organization.target_marketer_subscription_pricing_id %></td>
        <td><%= organization.target_marketer_billing_user_id %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Org src:</strong>
  <%= @organization.org_src_id %>
</p>

<p>
  <strong>Org:</strong>
  <%= @organization.org_id %>
</p>

<p>
  <strong>Account type:</strong>
  <%= @organization.account_type_id %>
</p>

<p>
  <strong>Created dt:</strong>
  <%= @organization.created_dt %>
</p>

<p>
  <strong>Modified dt:</strong>
  <%= @organization.modified_dt %>
</p>

<p>
  <strong>Created by user:</strong>
  <%= @organization.created_by_user_id %>
</p>

<p>
  <strong>Modified by user:</strong>
  <%= @organization.modified_by_user_id %>
</p>

<p>
  <strong>Target marketer bit:</strong>
  <%= @organization.target_marketer_bit %>
</p>

<p>
  <strong>Target marketer subscription pricing:</strong>
  <%= @organization.target_marketer_subscription_pricing_id %>
</p>

<p>
  <strong>Target marketer billing user:</strong>
  <%= @organization.target_marketer_billing_user_id %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>