config/routes.rb
Rails.application.routes.draw do
  resources :organization_contracts

  resources :organizations

  resources :user_events

  resources :users

  resources :event_facebook_pages

  resources :events

  resources :facebook_pages

end

app/models/organization_contract.rb
class OrganizationContract < ActiveRecord::Base
  self.table_name = 'OrganizationContracts'
end

app/controllers/organization_contracts_controller.rb
class OrganizationContractsController < ApplicationController
  before_action :set_organization_contract, only: [:show, :edit, :update, :destroy]

  # GET /organization_contracts
  # GET /organization_contracts.json
  def index
    @organization_contracts = OrganizationContract.all
  end

  # GET /organization_contracts/1
  # GET /organization_contracts/1.json
  def show
  end

  # GET /organization_contracts/new
  def new
    @organization_contract = OrganizationContract.new
  end

  # GET /organization_contracts/1/edit
  def edit
  end

  # POST /organization_contracts
  # POST /organization_contracts.json
  def create
    @organization_contract = OrganizationContract.new(organization_contract_params)

    respond_to do |format|
      if @organization_contract.save
        format.html { redirect_to @organization_contract, notice: 'Organization contract was successfully created.' }
        format.json { render :show, status: :created, location: @organization_contract }
      else
        format.html { render :new }
        format.json { render json: @organization_contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organization_contracts/1
  # PATCH/PUT /organization_contracts/1.json
  def update
    respond_to do |format|
      if @organization_contract.update(organization_contract_params)
        format.html { redirect_to @organization_contract, notice: 'Organization contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization_contract }
      else
        format.html { render :edit }
        format.json { render json: @organization_contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organization_contracts/1
  # DELETE /organization_contracts/1.json
  def destroy
    @organization_contract.destroy
    respond_to do |format|
      format.html { redirect_to organization_contracts_url, notice: 'Organization contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization_contract
      @organization_contract = OrganizationContract.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_contract_params
      params.require(:organization_contract).permit(:organization_id, :contract_id, :signed_by_user_id, :signed_dt, :created_dt, :modified_dt)
    end
end

app/helpers/organization_contracts_helper.rb
module OrganizationContractsHelper
end

app/views/organization_contracts/_form.html.erb
<%= form_for(@organization_contract) do |f| %>
  <% if @organization_contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization_contract.errors.count, "error") %> prohibited this organization_contract from being saved:</h2>

      <ul>
      <% @organization_contract.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organization_id %><br>
    <%= f.number_field :organization_id %>
  </div>
  <div class="field">
    <%= f.label :contract_id %><br>
    <%= f.number_field :contract_id %>
  </div>
  <div class="field">
    <%= f.label :signed_by_user_id %><br>
    <%= f.number_field :signed_by_user_id %>
  </div>
  <div class="field">
    <%= f.label :signed_dt %><br>
    <%= f.datetime_select :signed_dt %>
  </div>
  <div class="field">
    <%= f.label :created_dt %><br>
    <%= f.datetime_select :created_dt %>
  </div>
  <div class="field">
    <%= f.label :modified_dt %><br>
    <%= f.datetime_select :modified_dt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organization_contracts/edit.html.erb
<h1>Editing Organization Contract</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization_contract %> |
<%= link_to 'Back', organization_contracts_path %>

app/views/organization_contracts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organization Contracts</h1>

<table>
  <thead>
    <tr>
      <th>Organization</th>
      <th>Contract</th>
      <th>Signed by user</th>
      <th>Signed dt</th>
      <th>Created dt</th>
      <th>Modified dt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organization_contracts.each do |organization_contract| %>
      <tr>
        <td><%= organization_contract.organization_id %></td>
        <td><%= organization_contract.contract_id %></td>
        <td><%= organization_contract.signed_by_user_id %></td>
        <td><%= organization_contract.signed_dt %></td>
        <td><%= organization_contract.created_dt %></td>
        <td><%= organization_contract.modified_dt %></td>
        <td><%= link_to 'Show', organization_contract %></td>
        <td><%= link_to 'Edit', edit_organization_contract_path(organization_contract) %></td>
        <td><%= link_to 'Destroy', organization_contract, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization contract', new_organization_contract_path %>

app/views/organization_contracts/new.html.erb
<h1>New Organization Contract</h1>

<%= render 'form' %>

<%= link_to 'Back', organization_contracts_path %>

app/views/organization_contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organization:</strong>
  <%= @organization_contract.organization_id %>
</p>

<p>
  <strong>Contract:</strong>
  <%= @organization_contract.contract_id %>
</p>

<p>
  <strong>Signed by user:</strong>
  <%= @organization_contract.signed_by_user_id %>
</p>

<p>
  <strong>Signed dt:</strong>
  <%= @organization_contract.signed_dt %>
</p>

<p>
  <strong>Created dt:</strong>
  <%= @organization_contract.created_dt %>
</p>

<p>
  <strong>Modified dt:</strong>
  <%= @organization_contract.modified_dt %>
</p>

<%= link_to 'Edit', edit_organization_contract_path(@organization_contract) %> |
<%= link_to 'Back', organization_contracts_path %>